baseURL = 'https://ttakuji.netlify.app/'
languageCode = 'en-us'

theme = "hugo-theme-codex"
description = "Blog and Portifolio"
[params]
  github = "https://github.com/ttakuji"
  linkedin = "https://www.linkedin.com/in/yohan-takai/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"