baseURL = 'https://ttakuji.netlify.app/'
languageCode = 'en-us'
title = 'Yohan Takuji Takai'

theme = "archie"
description = "Blog and Portifolio"
[params]
  github = "https://github.com/ttakuji"
  linkedin = "https://www.linkedin.com/in/yohan-takai/"

[languages]
  [languages.en]
    weight = 1
    contentDir = "content/en"
    languageName = "English"
[[languages.en.menu.main]]
    identifier = "blog"
    name = "blog"
    title = "Blog"
    url = "/blog"
[[languages.en.menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about"
    [[languages.en.menu.main]]
    weight = 2
    identifier = "pt"
    name = "🇧🇷 Pt"
    title = "Português"
    url = "/pt-br"
  [languages.pt-br]
    weight = 2
    contentDir = "content/pt-br"
    languageName = "Português"
[[languages.pt-br.menu.main]]
     identifier = "blog"
     name = "meu blog"
     title = "Blog"
     url = "/pt-br/blog"

  [[languages.pt-br.menu.main]]
    weight = 2
    identifier = "en"
    name = "🇮🇪 En"
    title = "English"
    url = "/"